<a href="https://colab.research.google.com/github/Gobihanath/IMDB_Movies_Reviews_Prediction_NLP/blob/main/IMDB_Movies_Reviews_Prediction_NLP_Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

!ln -s /content/gdrive/My\ Drive/ /mydrive
!ls /mydrive

Mounted at /content/gdrive
'Colab Notebooks'   DataSets   DataSets-ML   ML_Trained_Models	'Projects Demo'   Test-1.jpg


In [ ]:
%cd /mydrive/DataSets/

/content/gdrive/My Drive/DataSets


In [ ]:
import pandas as pd
df = pd.read_csv("IMDB Dataset.csv")

In [ ]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding,LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
df.head(10)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [ ]:
df.describe()

review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [ ]:
df.shape


(50000, 2)

In [ ]:
df.tail()

review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [ ]:
df["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [ ]:
#replace sentiment column into integers // encoding
df.replace({"sentiment":{'positive':1,'negative':0}},inplace=True)

In [ ]:
df.head()

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [ ]:
train_data,test_data = train_test_split(df,test_size=0.2,random_state=42)

In [ ]:
train_data.shape


(40000, 2)

In [ ]:
test_data.shape

(10000, 2)

In [ ]:
#Tokenize text data

tokenizer = Tokenizer(num_words=5000)   #converting words into numbers
tokenizer.fit_on_texts(train_data["review"])

In [ ]:
X_train = pad_sequences(tokenizer.texts_to_sequences(train_data["review"]),maxlen=200)
X_test = pad_sequences(tokenizer.texts_to_sequences(test_data["review"]),maxlen=200)

In [ ]:
print(X_train)

[[1935    1 1200 ...  205  351 3856]
 [   3 1651  595 ...   89  103    9]
 [   0    0    0 ...    2  710   62]
 ...
 [   0    0    0 ... 1641    2  603]
 [   0    0    0 ...  245  103  125]
 [   0    0    0 ...   70   73 2062]]


In [ ]:
Y_train = train_data["sentiment"]
Y_test = test_data["sentiment"]

In [ ]:
Y_train

39087    0
30893    0
45278    1
16398    0
13653    0
        ..
11284    1
44732    1
38158    0
860      1
15795    1
Name: sentiment, Length: 40000, dtype: int64

In [ ]:
#LSTM - Long Short term memory

model =Sequential()
model.add(Embedding(input_dim=5000,output_dim=128,input_length=200))
model.add(LSTM(128,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(1,activation="sigmoid"))

model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 200, 128)          640000    
                                                                 
 lstm_1 (LSTM)               (None, 128)               131584    
                                                                 
 dense_1 (Dense)             (None, 1)                 129       
                                                                 
Total params: 771713 (2.94 MB)
Trainable params: 771713 (2.94 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [ ]:
model.fit(X_train,Y_train,epochs=10, batch_size=64,validation_split=0.2,verbose=2)

Epoch 1/10
500/500 - 431s - loss: 0.4149 - accuracy: 0.8043 - val_loss: 0.3066 - val_accuracy: 0.8746 - 431s/epoch - 862ms/step
Epoch 2/10
500/500 - 429s - loss: 0.2651 - accuracy: 0.8942 - val_loss: 0.2941 - val_accuracy: 0.8760 - 429s/epoch - 858ms/step
Epoch 3/10
500/500 - 427s - loss: 0.2261 - accuracy: 0.9120 - val_loss: 0.3579 - val_accuracy: 0.8681 - 427s/epoch - 854ms/step
Epoch 4/10
500/500 - 421s - loss: 0.1824 - accuracy: 0.9293 - val_loss: 0.3078 - val_accuracy: 0.8737 - 421s/epoch - 843ms/step
Epoch 5/10
500/500 - 426s - loss: 0.1663 - accuracy: 0.9370 - val_loss: 0.3276 - val_accuracy: 0.8794 - 426s/epoch - 852ms/step
Epoch 6/10
500/500 - 430s - loss: 0.1402 - accuracy: 0.9464 - val_loss: 0.4592 - val_accuracy: 0.8436 - 430s/epoch - 861ms/step
Epoch 7/10
500/500 - 428s - loss: 0.1377 - accuracy: 0.9490 - val_loss: 0.3528 - val_accuracy: 0.8748 - 428s/epoch - 856ms/step
Epoch 8/10
500/500 - 429s - loss: 0.1005 - accuracy: 0.9651 - val_loss: 0.4535 - val_accuracy: 0.8730 - 

In [24]:
loss,accuracy = model.evaluate(X_test,Y_test)

313/313 [==============================] - 32s 100ms/step - loss: 0.4525 - accuracy: 0.8726


In [25]:
model.save("/content/drive/MyDrive/ML_Trained_Models/imdb_model.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [36]:
def predict_sentiment(review):
  sequence = tokenizer.texts_to_sequences([review])
  padded_sequence = pad_sequences(sequence,maxlen=200)
  prediction = model.predict(padded_sequence)
  predicted_sentiment = "Positive" if prediction > 0.5 else "Negative"
  return predicted_sentiment,prediction


In [27]:
model = tf.keras.models.load_model("/content/drive/MyDrive/ML_Trained_Models/imdb_model.h5")

In [37]:
#testing

new_review = "This movie was terrible"
predicted_sentiment = predict_sentiment(new_review)
print(predicted_sentiment)


1/1 [==============================] - 0s 59ms/step
('Negative', array([[0.002357]], dtype=float32))


In [38]:
new_review = "I watched this drama this was so touched, it action mixed love drama,this drama makes me again and again"
predicted_sentiment = predict_sentiment(new_review)
print(predicted_sentiment)

1/1 [==============================] - 0s 68ms/step
('Positive', array([[0.9957906]], dtype=float32))


In [39]:
new_review = "Lost in the Shadows promised a thrilling dive into the realm of psychological horror, but what it delivered was an incoherent mess that left viewers more confused than captivated. Directed by Jane Doe, this film is a prime example of how good intentions and a talented cast can be completely undermined by poor execution and a disjointed script.The movie centers around Sarah, played by the usually brilliant Emma Stone, who moves into a supposedly haunted house after the mysterious disappearance of her brother. From the outset, the plot is riddled with clichés and predictable twists that fail to build any real suspense or intrigue. Instead of crafting a compelling narrative, the film bombards the audience with an overabundance of jump scares and grotesque imagery that feels more desperate than terrifying"
predicted_sentiment = predict_sentiment(new_review)
print(predicted_sentiment)

1/1 [==============================] - 0s 68ms/step
('Negative', array([[0.00165799]], dtype=float32))


In [40]:
new_review = "this movie has a tragedic ending, this movie makes nostalgia feeling especially the sarcastic character reveals the plot of the movie "
predicted_sentiment = predict_sentiment(new_review)
print(predicted_sentiment)

1/1 [==============================] - 0s 100ms/step
('Positive', array([[0.9092937]], dtype=float32))


In [41]:
new_review = "The movie also has a genuinely cinematic instinct for when to linger on a moment and when to cut around it, or allude to it as something that occurred offscreen. A lot of the longer sequences are just extended interactions between the film’s two romantic leads, who have a pleasing banter but derive a lot of their chemistry from looking at each other with resentment, yearning, gratitude, or disappointment. You almost never get to see material of this sort play out at length in a film set in the American West. Or any kind of film."
predicted_sentiment = predict_sentiment(new_review)
print(predicted_sentiment)

1/1 [==============================] - 0s 59ms/step
('Positive', array([[0.89584494]], dtype=float32))


In [42]:
new_review = "A Disappointing Journey is a letdown from start to finish. The plot is predictable, filled with clichéd twists that strip away any excitement. Characters are one-dimensional with poorly defined motivations, and the dialogue is cringeworthy, riddled with clichés and awkward attempts at humor.The film's pacing is uneven, dragging in the first act and losing direction in the second. By the climax, any sense of urgency is gone. Even the visuals, despite a high budget, are underwhelming, with lackluster special effects and bland cinematography. The action scenes are poorly choreographed and fail to engage.The soundtrack is forgettable, doing little to enhance the experience. Overall, A Disappointing Journey fails to deliver on its promises, making it a film worth skipping. There are far better options out there for your time and money."
predicted_sentiment = predict_sentiment(new_review)
print(predicted_sentiment)

1/1 [==============================] - 0s 75ms/step
('Negative', array([[0.00071008]], dtype=float32))
